name: Rerender PDFs

on:
  push:
    branches: master
  pull_request:
    branches: master

  workflow_dispatch:

jobs:
  render_summary:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - run: sudo apt-get update

      - name: install svg to png
        run: sudo apt-get install librsvg2-bin

      - name: create list of all files
        id: files_list
        run: |
          cd md
          echo "files=$(printf '"md/%s" ' *.md)" >> $GITHUB_ENV

      - name: print all files
        run: echo compiling ${{ env.files }}

      - name: create docs folder if not exists
        run: mkdir -p docs

      - name: compile and merge pdfs
        uses: docker://pandoc/latex:2.9
        with:
          args: -V documentclass=report -V classoption=oneside -V geometry:vmargin=14.5mm -V lang:de --fail-if-warnings --output=docs/modsim_SS23_IN2010_merge.pdf ${{ env.files }}

      - uses: actions/upload-artifact@master
        with:
          name: modsim_SS23_IN2010_merge.pdf
          path: docs/modsim_SS23_IN2010_merge.pdf

  push_merged_pdfs:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [render_summary]

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@master

      - name: delete old pdfs if exists
        run: rm -f docs/*.pdf

      - uses: actions/download-artifact@master
        with:
          name: modsim_SS23_IN2010_merge.pdf
          path: docs

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs/*.pdf -f
          git commit -m "Update PDFs"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master